export const CREATE_PERSONA = 'CREATE_PERSONA';
export const CREATE_PERSONA_SUCCESS = 'CREATE_PERSONA_SUCCESS';
export const CREATE_PERSONA_ERROR = 'CREATE_PERSONA_ERROR';

export const GET_PERSONAS = 'GET_PERSONAS'
export const GET_PERSONAS_SUCCESS = 'GET_PERSONAS_SUCCESS'
export const GET_PERSONAS_ERROR = 'GET_PERSONAS_ERROR'

export const DELETE_PERSONA = 'DELETE_PERSONA';
export const DELETE_PERSONA_SUCCESS = 'DELETE_PERSONA_SUCCESS';
export const DELETE_PERSONA_ERROR = 'DELETE_PERSONA_ERROR';

export const UPDATE_PERSONA = 'UPDATE_PERSONA';
export const GET_UPDATE_PERSONA = 'GET_UPDATE_PERSONA';
export const UPDATE_PERSONA_SUCCESS = 'UPDATE_PERSONA_SUCCESS';
export const UPDATE_PERSONA_ERROR = 'UPDATE_PERSONA_ERROR';