export const CREATE_PERSONA = 'CREATE_PERSONA';
export const CREATE_PERSONA_SUCCESS = 'CREATE_PERSONA_SUCCESS';
export const CREATE_PERSONA_ERROR = 'CREATE_PERSONA_ERROR';

export const GET_PERSONAS = 'GET_PERSONAS'
export const GET_PERSONAS_SUCCESS = 'GET_PERSONAS_SUCCESS'
export const GET_PERSONAS_ERROR = 'GET_PERSONAS_ERROR'